### ISSUE TITLE
Develop the ability to read transactions unencrypted only for initiator

### ISSUE THREAD

**Issue by duncanjw** [hyperledger-labs/private-transaction-families#23]

**Comment by yoni-wolf** [comment]
commit 4570eb02f41ef9e7126dfd36e7191725dd66bb82 contains this code.
note also new example of read transaction script - Debug/client_reader/read_request_txn.py

The implementation is to allow only the admin to read the encrypted transaction payload, not the initiator of the transaction. This is because there is no way to detect only from the transaction payload who initiated it.
